baseurl = "http://vietch2612.github.io/myvanhotel-3/"
languageCode = "en-us"
title = "Khach san My Van"
theme = "creative"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Khách sạn Mỹ Văn"
	description = "Khách sạn giá rẻ với tiện ích tuyệt vời."

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Khách sạn Mỹ Văn"

		[params.navigation.links]
			about     = "Giới thiệu"
			services  = "Giá phòng"
			portfolio = "Thư viện ảnh"
			contact   = "Liên hệ"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Khách sạn Mỹ Văn"
		subtitle   = "L17 khu biệt thự Á Châu, đường Hoàng Hoa Thám, Phường 2, Thành phố Vũng Tàu"
   	buttonText = "Xem thêm"


	# About section
	[params.about]
		headline    = "Giới thiệu về khách sạn Mỹ Văn"
		description = "MỸ VĂN HOTEL 7 tầng, gồm 18 phòng nghỉ, trong đó có 14phòng STANDAR ROOM ( 2 khách/ phòng) 4 phòng TWIN ROOM ( 4 khách/ phòng). Khách sạn có thang máy. Phục vụ 24/24. MỸ VĂN HOTEL nằm trong hẻm, hẻm kế bên quán cafe GARDEN, đặc biệt gần quán bánh khọt nổi tiếng Cây Vú Sữa, bánh khọt Cô Ba, cách bãi Thùy Vân 2km, cách chợ vũng Tàu, chợ xóm lưới bán hải sản tươi sống, bến xe khách Vũng Tàu (3 - 4 phút) chay xe máy. Cách trung tâm thành phố vũng tàu 5 phút xe máy."
		buttonText = "Đặt phòng"


	# Service section
	[params.services]
		headline = "Tại sao lại chọn khách sạn Mỹ Văn?"

        [[params.services.list]]
            icon = "fa-singleroom"
            title = "Standard room"
            description = "2 Người lớn + 1 Em bé dưới 6 tuổi. \nGiá ngày thường CN đến T6 200.000VND. \nThứ 7: 450.000VND - 700.000VND"

        [[params.services.list]]
			icon = "fa-doubleroom"
			title = "Twin room"
			description = "4 Người. Giá ngày thường CN đến T6: 350.000VND - 400.000VND. Thứ 7: 800.000VND - 1.500.000VND"

		[[params.services.list]]
            icon = "fa-car"
            title = "Chỗ để xe hơi"
            description = "Bạn đi xe hơi và lo lắng k có chỗ để, hãy yên tâm vì chúng tôi có chỗ để xe hơi cho bạn rồi."

        [[params.services.list]]
            icon = "fa-smile-o"
            title = "Thái độ phục vụ"
            description = "Bạn sẽ nhận được những nụ cười thân thiện nhất từ khách sạn."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"


    # Aside section
	[params.aside]
		headline = "Đặt phòng ngay bây giờ để có phòng tốt nhất với mức giá tốt nhất"
		# normalday = "Đơn: Standard 2PAX/Phòng, Chủ nhật đến T2 150.000VND đến 200.000VND"

		[params.aside.button]
			text = "Đặt phòng"
			link = "//www.agoda.com/my-van-hotel/hotel/vung-tau-vn.html"

	# Contact section
	[params.contact]
		headline = "Liên hệ với chúng tôi ngay"
		description = "Nếu bạn có bất cứ câu hỏi nào về khách sạn chúng tôi về phòng ngủ, chế độ phục vụ, dịch vụ thì hãy liên hệ ngay với chúng tôi bằng thông tin dưới đây"
		phone = "(+84) 121-4-857-794"
		email = "khachsanmyvan@gmail.com"
    	address = "L17 khu biệt thự Á Châu, Hoàng Hoa Thám, Phường 2, T.P Vũng Tàu"
